platform :ios, '9.0'

target 'CWWeibo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CWWeibo

end

pod 'AFNetworking'
pod 'SDWebImage/GIF'
pod 'SVProgressHUD'
pod 'SnapKit'
pod 'MJRefresh'
